# Generated by Django 4.0.8 on 2023-01-29 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(-1, '已删除'), (0, '已隐藏'), (1, '正常')], null=True, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男')], null=True, verbose_name='性别')),
                ('birthday', models.DateField(null=True, verbose_name='生日')),
                ('lunar_birthday', models.CharField(max_length=10, null=True, verbose_name='农历生日')),
                ('description', models.TextField(null=True, verbose_name='描述')),
                ('signature', models.TextField(null=True, verbose_name='个性签名')),
                ('real', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, null=True, verbose_name='是否已实名')),
                ('id_number', models.CharField(max_length=255, null=True, verbose_name='身份证号')),
                ('create_user', models.IntegerField(null=True)),
                ('update_user', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '个人信息表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(-1, '已删除'), (0, '已隐藏'), (1, '正常')], null=True, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='角色名')),
                ('description', models.TextField(null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '角色表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(-1, '已删除'), (0, '已隐藏'), (1, '正常')], null=True, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('avatar', models.ImageField(null=True, upload_to='avatar/', verbose_name='头像')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='用户名')),
                ('mobile', models.CharField(max_length=50, null=True, verbose_name='手机号')),
                ('mail', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=255, null=True, verbose_name='密码')),
                ('admin', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, null=True, verbose_name='是否是管理员')),
                ('last_login', models.DateTimeField(null=True, verbose_name='上次登录时间')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_UsersCreated_related', to='system.user')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_Users_related', to='system.person', verbose_name='实名信息')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_UsersUpdated_related', to='system.user')),
            ],
            options={
                'verbose_name': '用户表',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(-1, '已删除'), (0, '已隐藏'), (1, '正常')], null=True, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('related_roles', models.TextField(null=True, verbose_name='关联角色')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_UserRolesCreated_related', to='system.user')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_UserRolesUpdated_related', to='system.user')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_UserRoles_related', to='system.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户角色表',
                'db_table': 'system_user_role',
            },
        ),
        migrations.CreateModel(
            name='RoleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(-1, '已删除'), (0, '已隐藏'), (1, '正常')], null=True, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('related_accesses', models.TextField(null=True, verbose_name='关联权限')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_RoleMenusCreated_related', to='system.user')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_RoleMenus_related', to='system.role', verbose_name='角色')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_RoleMenusUpdated_related', to='system.user')),
            ],
            options={
                'verbose_name': '角色权限表',
                'db_table': 'system_role_access',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_RolesCreated_related', to='system.user'),
        ),
        migrations.AddField(
            model_name='role',
            name='update_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_RolesUpdated_related', to='system.user'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(-1, '已删除'), (0, '已隐藏'), (1, '正常')], null=True, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='名称')),
                ('url', models.CharField(max_length=50, null=True, verbose_name='映射地址')),
                ('icon', models.CharField(max_length=50, null=True, verbose_name='图标')),
                ('index', models.IntegerField(default=0, verbose_name='排序')),
                ('description', models.TextField(null=True, verbose_name='描述')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_MenusCreated_related', to='system.user')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_Menus_related', to='system.menu', verbose_name='父菜单')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_MenusUpdated_related', to='system.user')),
            ],
            options={
                'verbose_name': '菜单表',
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(-1, '已删除'), (0, '已隐藏'), (1, '正常')], null=True, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='名称')),
                ('url', models.CharField(max_length=50, null=True, verbose_name='映射地址')),
                ('description', models.TextField(null=True, verbose_name='描述')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_AccessesCreated_related', to='system.user')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_Accesses_related', to='system.menu', verbose_name='关联菜单')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_AccessesUpdated_related', to='system.user')),
            ],
            options={
                'verbose_name': '权限表',
            },
        ),
    ]
