"""
Django settings for worldlet project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/zh-hans/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/zh-hans/4.0/ref/settings/
"""
from os import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/zh-hans/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7l&xnjb81f-p*c&95c+-3ku*@ms0!n)ix@m9d&7j+!z!tzxid-'
# AES 密钥
AES_KEY = '2c8a01a556b1fbb0ee7852da5524bb7c'
# RSA 密钥，用于加密 RSA 私钥
RSA_KEY = '8eb6722b7c0c8ab7b6b17473a12a3683'
RSA_PRIVATE_KEY_PATH = BASE_DIR / 'secret/backend_private_key.pem'
RSA_PUBLIC_KEY_PATH = BASE_DIR / 'secret/backend_public_key.pem'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['127.0.0.1']
    STATIC_ROOT = 'static'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/zh-hans/4.0/howto/static-files/
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static/',
]

# 保存用户上传的文件目录的绝对文件系统路径
MEDIA_ROOT = environ.get('MEDIA_ROOT', '/userWorldlet/media/')
# 处理从 MEDIA_ROOT 提供的媒体的 URL，用于管理存储文件
MEDIA_URL = '/media/'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'system.apps.SystemConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'worldlet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'worldlet.wsgi.application'

# Database
# https://docs.djangoproject.com/zh-hans/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',

        'ENGINE': 'django.db.backends.mysql',
        # 'NAME': 'worldlet',
        'NAME': 'worldlet_test',
        'USER': 'kylin',
        'PASSWORD': 'Kylin@Worldlet',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/zh-hans/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/zh-hans/4.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# 用于序列化会话数据的序列化器类的完整导入路径，默认为 'django.contrib.sessions.serializers.JSONSerializer'
# SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

# 默认的主键字段类型，用于没有带有 primary_key=True 字段的模型，默认为 'django.db.models.AutoField'
# https://docs.djangoproject.com/zh-hans/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# XFrameOptionsMiddleware 使用的 X-Frame-Options 头的默认值，默认为 'DENY'
X_FRAME_OPTIONS = 'SAMEORIGIN'

# 免登录地址
LOGIN_SKIPPED_URLS = []
